### ISSUE TITLE
Imports error when trying to import client

### ISSUE THREAD

**Issue by finlayrichardson** [theusaf/KahootPY#12]
**Describe the bug**
When I try to run a simple script joining a game, it gives me an import error.

**To Reproduce**
```
from kahoot import client

pin = 3146584
bot = client()
bot.join(pin, "test")


def joined():
    print("joined")
```

When I run this script it gives me the error.

**Expected behavior**
I expected it to join the game.

**Error Message**
```
Traceback (most recent call last):
  File "kahoot.py", line 1, in <module>
    from kahoot import client
  File "/home/fr3shby/kahoot.py", line 1, in <module>
    from kahoot import client
ImportError: cannot import name 'client' from partially initialized module 'kahoot' (most likely due to a circular import) (/home/fr3shby/kahoot.py)
```

**Comment by finlayrichardson** [comment]
My bad, I just realised the error is caused by naming my script `kahoot.py`.
